# Linux antigen file
source ~/.antigen.zsh

export EDITOR="vim"
export TERM="xterm-256color"
export DOTFILES=$HOME/.dotfiles
source $DOTFILES/zsh/aliases.zsh

# PROMPT
SPACESHIP_CHAR_SYMBOL="➜  "
SPACESHIP_BATTERY_SHOW=false
SPACESHIP_VI_MODE_SHOW=true
SPACESHIP_HOST_SHOW=always

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Load the theme
antigen theme https://github.com/denysdovhan/spaceship-zsh-theme spaceship

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git 
antigen bundle command-not-found
antigen bundle autojump
antigen bundle common-aliases
antigen bundle compleat
antigen bundle git-extras
antigen bundle git-flow
antigen bundle z
antigen bundle vi-mode
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search ./zsh-history-substring-search.zsh

# Tell Antigen that you're done.
antigen apply

# Setup zsh-autosuggestions
source "$HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh" 

#fix home end etc behavior
#autoload zkbd
#[[ ! -f ${ZDOTDIR:-$HOME}/.zkbd/$TERM ]] && zkbd
#source ${ZDOTDIR:-$HOME}/.zkbd/$TERM
#
#[[ -n ${key[Backspace]} ]] && bindkey "${key[Backspace]}" backward-delete-char
#[[ -n ${key[Insert]} ]] && bindkey "${key[Insert]}" overwrite-mode
#[[ -n ${key[Home]} ]] && bindkey "${key[Home]}" beginning-of-line
#[[ -n ${key[PageUp]} ]] && bindkey "${key[PageUp]}" history-beginning-search-backward
#[[ -n ${key[Delete]} ]] && bindkey "${key[Delete]}" delete-char
#[[ -n ${key[End]} ]] && bindkey "${key[End]}" end-of-line
#[[ -n ${key[PageDown]} ]] && bindkey "${key[PageDown]}" history-beginning-search-forward
#[[ -n ${key[Up]} ]] && bindkey "${key[Up]}" history-beginning-search-backward
#[[ -n ${key[Left]} ]] && bindkey "${key[Left]}" backward-char
#[[ -n ${key[Down]} ]] && bindkey "${key[Down]}" history-beginning-search-forward
#[[ -n ${key[Right]} ]] && bindkey "${key[Right]}" forward-char

#fix for older non debian terminals:
#bindkey "^[OH" beginning-of-line
#bindkey "^[OF" end-of-line

